version: '3.1'
services:
  web:
    image: dwools/nginx:aesthetic_pivotal_tracker
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
  app:
    image: dwools/node:aesthetic_pivotal_tracker
    build: ./
    restart: always
    ports:
      - "8000:8000"
    command: gunicorn -b 0.0.0.0:8000 app:app
