version: '3.1'
services:
  web:
    image: dwools/nginx:aesthetic_pivotal_tracker
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
    profiles: ['production']

  app:
    image: dwools/flask:aesthetic_pivotal_tracker
    build: ./
    restart: always
    ports:
      - "8000:8000"
    # entrypoint: ["./entrypoint.sh"]
    command: ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]
    profiles: ['production']
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dwools:password@db:5432/pglogindb

  app-test:
    image: dwools/flask:aesthetic_pivotal_tracker
    build: ./
    restart: always
    volumes:
      - ./:/local
    ports:
      - "5000:5000"
    # entrypoint: ["./entrypoint.sh"]
    command: python3 /local/app_test.py
    profiles: ['test']
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dwools:password@db:5432/pglogindb

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: dwools
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pglogindb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    profiles: ["test", "production"]

networks:
  default:
    driver: bridge
